---
abstract: 'use L<Cpanel::JSON::XS> with a fallback to L<JSON::PP>'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Test::More: 0.88
  Test::Without::Module: 0.17
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-MaybeXS
no_index:
  directory:
    - t
    - inc
requires:
  Cpanel::JSON::XS: 2.3310
  JSON::PP: 2.27202
  Test::More: 0.88
  Test::Without::Module: 0.17
version: 1.001000
