---
abstract: 'Use L<Cpanel::JSON::XS> with a fallback to L<JSON::XS> and L<JSON::PP>'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Test::More: '0.88'
  Test::Without::Module: '0.17'
configure_requires:
  ExtUtils::CBuilder: '0.27'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-MaybeXS
no_index:
  directory:
    - t
    - inc
recommends:
  Cpanel::JSON::XS: '2.3310'
requires:
  JSON::PP: '2.27202'
  Safe::Isa: '0'
  perl: '5.006'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=JSON-MaybeXS
  repository: https://github.com/karenetheridge/JSON-MaybeXS.git
version: '1.002004'
